### ISSUE TITLE
Minecraft 1.19 Support

### ISSUE THREAD

**Issue by herby2212** [herby2212/TTA#4]
**Is your feature request related to a problem? If so please describe.**
No problem.

**Describe the solution you'd like**
Support for minecraft 1.19.

**Comment by rad1914** [comment]
Hi.. I got this when enabling TTA & FakePlayers in Paper 1.19..
https://pastebin.com/PRcdAvED
I'm not sure if that's an error.

**Comment by herby2212** [comment]
> Hi.. I got this when enabling TTA & FakePlayers in Paper 1.19.. https://pastebin.com/PRcdAvED I'm not sure if that's an error.

The error in FakePlayers is normal. As TTA disabled itself before, because a unsupported version was detected.

**Comment by herby2212** [comment]
Implemented with TTA 5.4.
